# Tensorflow Keras

This notebook shows how to solve a trivial problem by creating a network using tf.keras

### Import the needed modules

In [1]:
import numpy as np
import tensorflow as tf
import random

### Define the connections of the nodes in the network

In [2]:
input_ = tf.keras.layers.Input(shape=(2,))
dense1 = tf.keras.layers.Dense(2, activation='relu')(input_)
dense2 = tf.keras.layers.Dense(5, activation='relu')(dense1)
output = tf.keras.layers.Dense(1)(dense2)

### Define a model from the input node to the last dense node

In [3]:
model = tf.keras.Model(inputs=input_, outputs=output)

### Verify the structure of the created model

In [4]:
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 2)]               0         
_________________________________________________________________
dense (Dense)                (None, 2)                 6         
_________________________________________________________________
dense_1 (Dense)              (None, 5)                 15        
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 6         
Total params: 27
Trainable params: 27
Non-trainable params: 0
_________________________________________________________________


### Compile the model by providing the optimization algorithm and the loss function

In [5]:
model.compile('adam', 'mse')

### Define the non linear toy problem to check if the network will work

In [6]:
def function(x, y):
    return 5*x**2 - 3*y**2 + 3

### Generate random values and calculate the label using the toy problem

In [7]:
X = np.random.rand(100, 2)
y = function(X[:,0], X[:,1])

### View the generated values

In [8]:
X[:, 0] # access first column

array([4.76859571e-01, 6.79370648e-01, 4.47693876e-01, 1.96391834e-01,
       9.04118613e-01, 8.55148852e-01, 5.23976886e-02, 6.65236108e-01,
       6.71303953e-01, 6.26966645e-01, 7.40758869e-01, 7.51441248e-01,
       2.55649553e-01, 9.35489224e-01, 3.40019487e-01, 3.61807936e-03,
       8.27747139e-01, 6.09520600e-01, 3.08740684e-01, 9.60158835e-01,
       6.61895555e-01, 7.86267362e-01, 8.36206365e-02, 3.20008392e-01,
       4.13336145e-01, 5.16648266e-01, 1.91020786e-01, 9.34240668e-01,
       8.96383258e-01, 6.57125784e-01, 8.99219770e-01, 6.08474083e-01,
       2.63991878e-01, 1.59228849e-01, 3.73634339e-01, 5.66410664e-01,
       9.28030994e-01, 5.90824690e-01, 4.29266724e-01, 4.58279984e-01,
       7.15205477e-01, 8.83171538e-01, 2.82334860e-01, 9.62155147e-02,
       8.16790632e-01, 8.95926230e-01, 1.24994571e-01, 7.57660684e-02,
       7.04086656e-01, 1.95994011e-02, 4.12214012e-01, 6.31537806e-02,
       2.22690104e-01, 2.78353452e-01, 3.69394881e-01, 3.18333138e-01,
      

In [9]:
X[:, 1] # access second column

array([0.36462078, 0.16924806, 0.43828361, 0.95488013, 0.33471248,
       0.21487498, 0.02221049, 0.92288927, 0.87055751, 0.38118532,
       0.90188   , 0.37499678, 0.27334457, 0.13094631, 0.31492761,
       0.452655  , 0.81265539, 0.74116299, 0.12447709, 0.62178782,
       0.22790012, 0.77789014, 0.64863578, 0.97256907, 0.02712344,
       0.79884464, 0.34932496, 0.91554295, 0.60490065, 0.01710451,
       0.68475984, 0.71252671, 0.34912757, 0.74288037, 0.94014627,
       0.74715141, 0.21909503, 0.08482599, 0.23938369, 0.25212235,
       0.21555603, 0.59748248, 0.98845126, 0.50001894, 0.29937268,
       0.74208637, 0.51760335, 0.61849079, 0.99743275, 0.72184642,
       0.93685812, 0.36875348, 0.14686673, 0.13592577, 0.16301788,
       0.03121545, 0.22588304, 0.91487204, 0.04295673, 0.7195668 ,
       0.32042415, 0.74916742, 0.45102513, 0.11775912, 0.55477859,
       0.89456286, 0.4580484 , 0.09790294, 0.97527049, 0.02993617,
       0.09338254, 0.73969172, 0.13482585, 0.94854447, 0.65793

In [10]:
y

array([3.73813031, 5.22178767, 3.42587147, 0.45746058, 6.75105501,
       6.51788402, 3.01224767, 2.65752156, 2.97963383, 4.52952913,
       3.30345593, 5.40145199, 3.1026317 , 7.32425964, 3.28052806,
       2.38537582, 4.44460028, 3.20960906, 3.43012041, 6.44966465,
       5.03471324, 4.27574263, 1.77277691, 0.67435509, 3.8520268 ,
       2.42016888, 2.81636092, 4.84937145, 5.91980035, 5.15819379,
       5.63629288, 3.3281206 , 2.98278839, 1.4711554 , 1.04638805,
       2.92939949, 7.16219973, 4.72378273, 3.74943595, 3.85940568,
       5.41820116, 5.82900388, 0.46745719, 2.29623031, 6.06686268,
       5.36134252, 2.27437853, 1.8811099 , 2.4940738 , 1.43873394,
       1.21649254, 2.61200462, 3.1832449 , 3.33197578, 3.60253841,
       3.50375672, 3.90052026, 1.07587475, 5.7643139 , 2.40617821,
       4.96237917, 4.8761926 , 2.81112064, 3.0097074 , 6.46636434,
       3.45448458, 4.70947994, 2.97124525, 2.38452159, 5.17649433,
       2.97512195, 4.63235056, 4.12580995, 0.38164861, 3.24598

In [11]:
model.fit(X, y, batch_size=4, epochs=100)

Train on 100 samples
Epoch 1/100
100/100 [==============================] - 0s 5ms/sample - loss: 15.4708
Epoch 2/100
100/100 [==============================] - 0s 718us/sample - loss: 14.5418
Epoch 3/100
100/100 [==============================] - 0s 695us/sample - loss: 13.5442
Epoch 4/100
100/100 [==============================] - 0s 669us/sample - loss: 12.5428
Epoch 5/100
100/100 [==============================] - 0s 794us/sample - loss: 11.4872
Epoch 6/100
100/100 [==============================] - 0s 801us/sample - loss: 10.4190
Epoch 7/100
100/100 [==============================] - 0s 912us/sample - loss: 9.3232
Epoch 8/100
100/100 [==============================] - 0s 671us/sample - loss: 8.2964
Epoch 9/100
100/100 [==============================] - 0s 694us/sample - loss: 7.2680
Epoch 10/100
100/100 [==============================] - 0s 735us/sample - loss: 6.3387
Epoch 11/100
100/100 [==============================] - 0s 874us/sample - loss: 5.4635
Epoch 12/100
100/100 [=====

100/100 [==============================] - 0s 482us/sample - loss: 0.1948
Epoch 96/100
100/100 [==============================] - 0s 465us/sample - loss: 0.1946
Epoch 97/100
100/100 [==============================] - 0s 398us/sample - loss: 0.1935
Epoch 98/100
100/100 [==============================] - 0s 432us/sample - loss: 0.1916
Epoch 99/100
100/100 [==============================] - 0s 425us/sample - loss: 0.1906
Epoch 100/100
100/100 [==============================] - 0s 421us/sample - loss: 0.1904


### Predict the label using the model and verify the result

In [12]:
predictions = model.predict(X)

In [13]:
predictions[:5] # first 5 rows

array([[4.1641088],
       [5.4552884],
       [3.7358775],
       [1.1790856],
       [6.1955395]], dtype=float32)

In [14]:
y[:5] # first 5 rows

array([3.73813031, 5.22178767, 3.42587147, 0.45746058, 6.75105501])

### The loss can also be calculated using the ```evaluate``` function

In [15]:
model.evaluate(X, y)

100/100 [==============================] - 0s 566us/sample - loss: 0.1880


0.18799112200737