In [49]:
from keras.models import Model
from keras.layers import Dense, Input
from keras.optimizers import SGD
from keras.losses import binary_crossentropy
from keras.activations import relu
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder

In [5]:
CSV_PATH='msft_malware/train.csv'

In [8]:
df = pd.read_csv(CSV_PATH, nrows=10000)

In [12]:
y = df['HasDetections'].values

In [48]:
y

array([0, 0, 0, ..., 1, 1, 0], dtype=int64)

In [14]:
df.head(5)

MachineIdentifier      ...      HasDetections
0  0000028988387b115f69f31a3bf04f09      ...                  0
1  000007535c3f730efa9ea0b7ef1bd645      ...                  0
2  000007905a28d863f6d0d597892cd692      ...                  0
3  00000b11598a75ea8ba1beea8459149f      ...                  1
4  000014a5f00daa18e76b81417eeb99fc      ...                  1

[5 rows x 83 columns]

In [17]:
cols_to_use = ['ProductName', 'Platform', 'OsBuild']
X_raw = df[cols_to_use]
X_raw.head(5)

ProductName   Platform  OsBuild
0  win8defender  windows10    17134
1  win8defender  windows10    17134
2  win8defender  windows10    17134
3  win8defender  windows10    17134
4  win8defender  windows10    17134

In [28]:
X_raw['ProductName'].unique()

array(['win8defender', 'mse'], dtype=object)

In [25]:
onehot = OneHotEncoder(sparse=False)

In [26]:
pname = X_raw['ProductName'].values.reshape(-1, 1)

In [30]:
onehot.fit(pname)
pname_encoded = onehot.transform(pname)

In [29]:
ordinal = OrdinalEncoder()
ordinal.fit_transform(pname)

array([[1.],
       [1.],
       [1.],
       ...,
       [1.],
       [1.],
       [1.]])

In [32]:
X_raw['Platform'].unique()

array(['windows10', 'windows7', 'windows8', 'windows2016'], dtype=object)

In [37]:
platform = X_raw['Platform'].values.reshape(-1, 1)
onehot2 = OneHotEncoder(sparse=False)
platform_encoded = onehot2.fit_transform(platform)

In [36]:
ordinal2 = OrdinalEncoder()
ordinal2.fit_transform(platform)

array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [0.]])

In [40]:
osbuild = X_raw['OsBuild'].values.reshape(-1, 1)
onehot3 = OneHotEncoder(sparse=False, categories='auto')
osbuild_encoded = onehot3.fit_transform(osbuild)

In [42]:
X = np.concatenate([pname_encoded, platform_encoded, osbuild_encoded], axis=1)
X

array([[0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       ...,
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.]])

In [43]:
X.shape

(10000, 29)

In [54]:
input_ = Input(shape=(29,))
dense1 = Dense(32, activation=relu)(input_)
dense2 = Dense(32, activation=relu)(dense1)
dense3 = Dense(32, activation=relu)(dense2)
output = Dense(1)(dense3)

In [45]:
model = Model(inputs=input_, outputs=output)

In [55]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 29)                0         
_________________________________________________________________
dense_1 (Dense)              (None, 32)                960       
_________________________________________________________________
dense_2 (Dense)              (None, 32)                1056      
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 33        
Total params: 2,049
Trainable params: 2,049
Non-trainable params: 0
_________________________________________________________________


In [56]:
model.compile(SGD(), binary_crossentropy)

In [57]:
model.fit(X, y, batch_size=32, epochs=100, )

Epoch 1/100
10000/10000 [==============================] - 0s 45us/step - loss: 0.6928
Epoch 2/100
10000/10000 [==============================] - 0s 27us/step - loss: 0.6923
Epoch 3/100
10000/10000 [==============================] - 0s 32us/step - loss: 0.6927
Epoch 4/100
10000/10000 [==============================] - 0s 28us/step - loss: 0.6929
Epoch 5/100
10000/10000 [==============================] - 0s 27us/step - loss: 0.6927
Epoch 6/100
10000/10000 [==============================] - 0s 27us/step - loss: 0.6924
Epoch 7/100
10000/10000 [==============================] - 0s 33us/step - loss: 0.6925
Epoch 8/100
10000/10000 [==============================] - 0s 31us/step - loss: 0.6924
Epoch 9/100
10000/10000 [==============================] - 0s 28us/step - loss: 0.6929
Epoch 10/100
10000/10000 [==============================] - 0s 27us/step - loss: 0.6927
Epoch 11/100
10000/10000 [==============================] - 0s 32us/step - loss: 0.6923
Epoch 12/100
10000/10000 [===============

10000/10000 [==============================] - 0s 34us/step - loss: 0.6926
Epoch 95/100
10000/10000 [==============================] - 0s 29us/step - loss: 0.6918
Epoch 96/100
10000/10000 [==============================] - 0s 27us/step - loss: 0.6926
Epoch 97/100
10000/10000 [==============================] - 0s 26us/step - loss: 0.6923
Epoch 98/100
10000/10000 [==============================] - 0s 28us/step - loss: 0.6923
Epoch 99/100
10000/10000 [==============================] - 0s 28us/step - loss: 0.6925
Epoch 100/100
10000/10000 [==============================] - 0s 28us/step - loss: 0.6923
